# Generated by Django 3.1 on 2021-05-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.EmailField(blank=True, max_length=254)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
