# Generated by Django 3.1 on 2021-06-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0002_doctordetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctordetails',
            old_name='EmailField',
            new_name='email',
        ),
    ]
