# Generated by Django 3.1 on 2021-06-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0005_doctorschedule_pharmacistschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAppointmentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnumber', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('doctor', models.CharField(max_length=20, null=True)),
                ('age', models.CharField(max_length=20, null=True)),
                ('emailid', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('reason', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
