# Generated by Django 3.2.4 on 2021-06-04 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0007_facultyappointmentform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treated', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.doctordetails')),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.pharmcistdetails')),
            ],
        ),
        migrations.AlterField(
            model_name='studentappointmentform',
            name='idnumber',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='StudentTreatment',
            fields=[
                ('treatment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='HMS.treatment')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.studentappointmentform')),
            ],
            bases=('HMS.treatment',),
        ),
        migrations.CreateModel(
            name='FacultyTreatment',
            fields=[
                ('treatment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='HMS.treatment')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.facultyappointmentform')),
            ],
            bases=('HMS.treatment',),
        ),
    ]
