# Generated by Django 3.2.4 on 2021-06-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0009_alter_treatment_pharmacist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('morning', models.BooleanField(default=False)),
                ('afternoon', models.BooleanField(default=False)),
                ('night', models.BooleanField(default=False)),
            ],
        ),
    ]
