# Generated by Django 3.2.4 on 2021-06-05 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0010_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMedicine',
            fields=[
                ('medicine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='HMS.medicine')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.studentappointmentform')),
            ],
            bases=('HMS.medicine',),
        ),
        migrations.CreateModel(
            name='FacultyMedicine',
            fields=[
                ('medicine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='HMS.medicine')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.facultyappointmentform')),
            ],
            bases=('HMS.medicine',),
        ),
    ]
