# Generated by Django 3.2.4 on 2021-06-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0011_facultymedicine_studentmedicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
