# Generated by Django 3.2.4 on 2021-06-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0012_treatment_rejected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='treated',
            new_name='completely_treated',
        ),
        migrations.AddField(
            model_name='treatment',
            name='doctor_treated',
            field=models.BooleanField(default=False),
        ),
    ]
