# Generated by Django 3.2.4 on 2021-06-05 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0014_auto_20210605_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultymedicine',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='studentmedicine',
            name='treatment',
        ),
    ]
